# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build
    jobs:
    - job: Build
      steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            goals: 'package'
            checkStyleRunAnalysis: true
            pmdRunAnalysis: true
            findBugsRunAnalysis: true
 
        -  task: CopyFiles@2
           displayName: 'Copy Files to artifact staging directory'
           inputs:
             SourceFolder: '$(System.DefaultWorkingDirectory)'
             Contents: '**/target/*.?(war|jar)'
             TargetFolder: $(Build.ArtifactStagingDirectory)

        - upload: $(Build.ArtifactStagingDirectory)
          artifact: drop
